package Task.Management.System.commands.enums;

public enum CommandType {
    CREATE_NEW_USER,
    SHOW_ALL_USERS,
    SHOW_USER_ACTIVITY,
    CREATE_NEW_TEAM,
    SHOW_ALL_TEAMS,
    SHOW_TEAM_ACTIVITY,
    ADD_USER_TO_TEAM,
    SHOW_ALL_USERS_IN_TEAM,
    CREATE_NEW_BOARD_IN_TEAM,
    SHOW_ALL_TEAM_BOARDS,
    SHOW_BOARD_ACTIVITY,
    CREATE_NEW_BUG_IN_TEAM_BOARD,
    CREATE_NEW_STORY_IN_TEAM_BOARD,
    CREATE_NEW_FEEDBACK_IN_TEAM_BOARD,
    CHANGE_BUG,
    CHANGE_STORY,
    CHANGE_FEEDBACK,
    ASSIGN_TASK_TO_USER,
    ADD_COMMENT_TO_TASK
}
