package Task.Management.System.commands.enums;

public enum CommandType {
    CREATE_NEW_PERSON,
    SHOW_ALL_PEOPLE,
    SHOW_PERSON_ACTIVITY,
    CREATE_NEW_TEAM,
    SHOW_ALL_TEAMS,
    SHOW_TEAM_ACTIVITY,
    ADD_PERSON_TO_TEAM,
    SHOW_ALL_TEAM_MEMBERS,
    CREATE_NEW_BOARD_IN_TEAM,
    SHOW_ALL_TEAM_BOARDS,
    SHOW_BOARD_ACTIVITY,
    CREATE_NEW_TASK_IN_BOARD,
    CHANGE_BUG,
    CHANGE_STORY,
    CHANGE_FEEDBACK,
    ASSIGN_TASK_TO_PERSON,
    ADD_COMMENT_TO_TASK
}
