package Task.Management.System.commands.enums;

public enum CommandType {
    CREATE_BOARD,
    CREATE_BUG,
    CREATE_STORY,
    CREATE_FEEDBACK,
    CREATE_TEAM,
    CREATE_USER,
    SHOW_ALL_USERS,
    SHOW_USER_ACTIVITY,
    SHOW_ALL_TEAMS,
    SHOW_TEAM_ACTIVITY,
    ADD_USER_TO_TEAM,
    SHOW_ALL_USERS_IN_TEAM,
    SHOW_ALL_TEAM_BOARDS,
    SHOW_BOARD_ACTIVITY,
    CHANGE_BUG,
    CHANGE_STORY,
    CHANGE_FEEDBACK,
    ASSIGN_TASK_TO_USER,
    ADD_COMMENT_TO_TASK,
}
